#!/usr/bin/env ansible-playbook

## Setup the stuff
---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Enable USB Gadget
      ansible.builtin.script: config/usb-gadget-setup.sh
    - name: Install bt-hid-proxy.service.j2
      ansible.builtin.template:
        src: config/bt-hid-proxy.service.j2
        dest: /etc/systemd/system/bt-hid-proxy.service
        owner: pi
        group: wheel
        mode: u=rw,g=r,o=r
    - name: Force systemd reload config
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Enable service bt-hid-proxy.service
      ansible.builtin.systemd:
        name: bt-hid-proxy.service
        enabled: yes
        masked: no